In [ ]:
### Section A
# 1. Create a list of 5 integers
nums = [10, 20, 30, 40, 50]
print("Original list:", nums)

# append
nums.append(60)
print("After append:", nums)

# extend
nums.extend([70, 80])
print("After extend:", nums)

# insert
nums.insert(2, 25)
print("After insert:", nums)

# remove
nums.remove(40)
print("After remove:", nums)

# pop
nums.pop()
print("After pop:", nums)

# index
print("Index of 30:", nums.index(30))

# count
print("Count of 20:", nums.count(20))

# sort
nums.sort()
print("After sort:", nums)

# reverse
nums.reverse()
print("After reverse:", nums)

# clear
nums.clear()
print("After clear:", nums)


Original list: [10, 20, 30, 40, 50]
After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove: [10, 20, 25, 30, 50, 60, 70, 80]
After pop: [10, 20, 25, 30, 50, 60, 70]
Index of 30: 3
Count of 20: 1
After sort: [10, 20, 25, 30, 50, 60, 70]
After reverse: [70, 60, 50, 30, 25, 20, 10]
After clear: []


In [3]:
##2.Tuple
students = ("Aisha", "Yasmeen", "Rahul")
print("Original tuple:", students)

# Trying to change second name
students[1] = "Nazeer"


Original tuple: ('Aisha', 'Yasmeen', 'Rahul')


TypeError: 'tuple' object does not support item assignment

In [6]:
###3.Set
A = {1, 2, 3, 4, 2, 3, 5}
print("Set:", A)


Set: {1, 2, 3, 4, 5}


In [7]:
#### 4. Dictnory
person = {
    "name": "Yasmeen",
    "age": 20,
    "city": "Hyderabad"
}

# Update age
person["age"] = 21

# Add new key
person["email"] = "yasmeen@gmail.com"

print("Final dictionary:", person)


Final dictionary: {'name': 'Yasmeen', 'age': 21, 'city': 'Hyderabad', 'email': 'yasmeen@gmail.com'}


In [5]:
## 5. Vote eligibility
age = int(input("Enter your age: "))

if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")


You are eligible to vote.


In [6]:
## 6. Grading
marks = int(input("Enter marks: "))

if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")


Grade: C


In [16]:
### 7
num = int(input("Enter a number: "))

if num > 0:
    print(f"{num} is positive")
    if num % 2 == 0:
        print(f"{num} is even")
    else:
        print(f"{num} is odd")
elif num == 0:
    print(f"{num} is zero")
else:
    print(f"{num} is negative")


46 is positive
46 is even


In [17]:
## Section C
## 8. Scalar,arrary
import numpy as np

# Scalar
scalar = np.array(5)
print("Scalar:")
print(scalar)

# 1D array with values 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])
print("\n1D Array:")
print(array_1d)

# 2D array (2x3) with values from 10 to 60 in steps of 10
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60]])
print("\n2D Array (2x3):")
print(array_2d)


Scalar:
5

1D Array:
[1 2 3 4 5]

2D Array (2x3):
[[10 20 30]
 [40 50 60]]


In [18]:
##9
import numpy as np

random_array = np.random.randint(0, 101, size=(4, 4))
print("4x4 Random Integer Array:")
print(random_array)


4x4 Random Integer Array:
[[27 28 76 93]
 [22 87 37 58]
 [81 50 42 60]
 [13 87 21 84]]


In [20]:
!pip install pandas


   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.3 MB 3.4 MB/s eta 0:00:04
   --- ------------------------------------ 1.0/11.3 MB 2.0 MB/s eta 0:00:06
   ----- ---------------------------------- 1.6/11.3 MB 2.6 MB/s eta 0:00:04
   ------- -------------------------------- 2.1/11.3 MB 2.3 MB/s eta 0:00:04
   --------- ------------------------------ 2.6/11.3 MB 2.4 MB/s eta 0:00:04
   ------------ --------------------------- 3.7/11.3 MB 2.8 MB/s eta 0:00:03
   ----------------- ---------------------- 5.0/11.3 MB 3.4 MB/s eta 0:00:02
   ------------------ --------------------- 5.2/11.3 MB 3.1 MB/s eta 0:00:02
   ------------------------ --------------- 6.8/11.3 MB 3.6 MB/s eta 0:00:02
   ----------------------------- ---------- 8.4/11.3 MB 4.0 MB/s eta 0:00:01
   ---------------------------------- ----- 9.7/11.3 MB 4.2 MB/s eta 0:00:01
   ----------


[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [21]:
%pip install pandas


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
###10
import numpy as np
import pandas as pd   # assume pandas is installed

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

df = pd.DataFrame(array_2d, columns=['A', 'B', 'C'])
print(df)


   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [25]:
## Section C
## 11. Exploring pandas
import pandas as pd

# Create DataFrame manually with 10 rows
data = {
    "Name": ["Aisha", "Yasmeen", "Rahul", "Fatima", "Ravi",
             "Neha", "Aisha", "Imran", "Sara", "Rahul"],
    "Age": [22, 21, 23, 20, 24, 22, 22, 25, 21, 23],
    "City": ["Hyderabad", "Delhi", "Mumbai", "Chennai", "Pune",
             "Delhi", "Hyderabad", "Bangalore", "Mumbai", "Mumbai"],
    "Salary": [45000, 50000, 48000, None, 52000,
               50000, 45000, None, 47000, 48000]
}

df = pd.DataFrame(data)

print("----- Original DataFrame -----")
print(df)

# DataFrame info
print("\n----- DataFrame Info -----")
df.info()

# Statistical description
print("\n----- DataFrame Describe -----")
print(df.describe())

# Select Name and City columns
print("\n----- Selected Columns (Name & City) -----")
print(df[['Name', 'City']])

# Drop City column
df = df.drop(columns=['City'])
print("\n----- After Dropping City Column -----")
print(df)

# Fill missing Salary values with mean
salary_mean = df['Salary'].mean()
df['Salary'].fillna(salary_mean, inplace=True)
print("\n----- After Filling Missing Salary Values -----")
print(df)

# Remove duplicate rows
df = df.drop_duplicates()
print("\n----- After Removing Duplicate Rows -----")
print(df)


----- Original DataFrame -----
      Name  Age       City   Salary
0    Aisha   22  Hyderabad  45000.0
1  Yasmeen   21      Delhi  50000.0
2    Rahul   23     Mumbai  48000.0
3   Fatima   20    Chennai      NaN
4     Ravi   24       Pune  52000.0
5     Neha   22      Delhi  50000.0
6    Aisha   22  Hyderabad  45000.0
7    Imran   25  Bangalore      NaN
8     Sara   21     Mumbai  47000.0
9    Rahul   23     Mumbai  48000.0

----- DataFrame Info -----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 448.0+ bytes

----- DataFrame Describe -----
             Age        Salary
count  10.000000      8.000000
mean   22.300000  48125.000000
std     1.494434   2474.873734

C:\Users\hp\AppData\Local\Temp\ipykernel_26948\1832520672.py:40: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(salary_mean, inplace=True)
